; Map Right Alt + qweasdzxcf to 1234567890
RAlt & q::Send, 1
RAlt & w::Send, 2
RAlt & e::Send, 3
RAlt & a::Send, 4
RAlt & s::Send, 5
RAlt & d::Send, 6
RAlt & z::Send, 7
RAlt & x::Send, 8
RAlt & c::Send, 9
RAlt & f::Send, 0
RAlt & v::Send, ,
RAlt & j::Send, {+}
RAlt & k::Send, -
RAlt & l::Send, =
RAlt & n::Send, *
RAlt & m::Send `%
RAlt & ,::Send, <
RAlt & .::Send, >
RAlt & Y::Send, #
RAlt & U::Send, {^}
RAlt & I::Send, $
RAlt & O::Send, @
RAlt & P::Send, &
RAlt & [::Send, |
;RWin & j::Send, (
;RWin & k::Send, )
;RWin & a::Send, [
;RWin & s::Send, :
;RWin & d::Send, ]
RWin & f::Send, "
;RWin & g::Send, '
;RWin & h::Send, -
;RWin & m::Send, ^
RWin & <::Send {{}
RWin & >::Send {}}
RWin::Send return
